server:
  port: 9806

spring:
  profiles:
    active: dev  
    
    # Database connection properties
  datasource:
    url: jdbc:postgresql://localhost:5433/book_club_user
    username: postgres
    password: postgres

# Logging SQL statements
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE



