eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      
      instance:
        preferIpAddress: true
      
server:
  port: 9802

jwt: 
  secret: helloasdasdasdasdadfdfsdfsdfasdasdawdawdasdasdwdasdaw
  expiration: 120000
  header: Authorization
  
spring:
  application:
    name: gateway-ms
    cloud:
    gateway:
      routes:
        - id: USER-MS
          uri: http://localhost:9806
          predicates:
            - Path=/user/**
    discovery:
      enabled: true
      
  main:
    web-application-type: reactive
  