eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      instance:
      preferIpAddress: true
server:
  port: 9802

spring:
  application:
    name: gateway-ms
    
    
#zuul:
#  routes:
#    service1:
#      path: /service1/**
#      serviceId: service1
#    service2:
#      path: /service2/**
#      serviceId: service2
#    service3:
#      path: /service3/**
#      serviceId: service3
